name: Example passing inputs and secrets to this reusable workflow

on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
      input2: 
        type: string
    secrets:
      mysecret1:
        required: true
      mysecret2:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2

      - name: Run Hello World
        run: |
            echo "Hello World!"
            echo "input1=${{ inputs.input1 }}"
            echo "input2=${{ inputs.input2 }}"
            echo "Dont echo secrets please.  mysecret1=${{secrets.mysecret1}}"
            echo "Dont echo secrets please.  mysecret2=${{secrets.mysecret2}}"
            
